ci:
    autofix_prs: false
    autoupdate_schedule: quarterly
repos:
        - repo: https://github.com/pre-commit/pre-commit-hooks
          rev: v4.3.0
          hooks:
                - id: check-yaml
                  exclude: ^original_code/|^tests/test_data/
                - id: end-of-file-fixer
                  exclude: ^original_code/|^tests/test_data/|\.txt$
                - id: trailing-whitespace
                  exclude: ^original_code/|^tests/test_data/
                - id: check-merge-conflict
                  exclude: ^original_code/|^tests/test_data/

        # Format the code aggressively using black
        - repo: https://github.com/psf/black
          rev: 24.4.0
          hooks:
                - id: black
                  exclude: ^original_code/|^tests/test_data/

        # Lint the code using flake8
        - repo: https://github.com/pycqa/flake8
          rev: 7.1.0
          hooks:
                - id: flake8
                  args: ["--config=.flake8", "--extend-ignore=E501,E722,E203,E207"]
                  exclude: ^original_code/|^tests/test_data/

        # Sort imports using isort
        - repo: https://github.com/PyCQA/isort
          rev: 5.12.0
          hooks:
                - id: isort
                  args: [ "--profile", "black" ]
                  exclude: ^original_code/|^tests/test_data/
