ci:
    autofix_prs: false
    autoupdate_schedule: quarterly
repos:
        - repo: https://github.com/pre-commit/pre-commit-hooks
          rev: v4.3.0
          hooks:
                - id: check-yaml
                - id: end-of-file-fixer
                  exclude: \.txt$
                - id: trailing-whitespace  # Remove trailing whitespaces
                - id: check-merge-conflict
        # Fix common spelling mistakes
        - repo: https://github.com/codespell-project/codespell
          rev: v2.2.1
          hooks:
                - id: codespell
                  args: [--ignore-words-list=alos, --ignore-regex=\bnin\b]
                  types_or: [python, rst, markdown]
                  files: ^(geoutils|doc|tests)/

        # Replace relative imports (e.g. 'from . import raster' -> 'from geoutils import raster')
        - repo: https://github.com/MarcoGorelli/absolufy-imports
          rev: v0.3.1
          hooks:
                - id: absolufy-imports

        # Format the code aggressively using black
        - repo: https://github.com/psf/black
          rev: 22.10.0
          hooks:
                  - id: black


        # Lint the code using flake8
        - repo: https://github.com/pycqa/flake8
          rev: 3.9.2
          hooks:
                - id: flake8

        # Sort imports using isort
        - repo: https://github.com/PyCQA/isort
          rev: 5.12.0
          hooks:
                  - id: isort
                    args: [ "--profile", "black" ]
