#!/usr/bin/env python3
"""Fail if a committed report PDF carries figures above the dpi ceiling.

The ceiling is enforced when the PDF is written (``asp_plot.report``
downsamples each figure to ``FIGURE_MAX_DPI`` at its placed width), so a report
generated by current asp_plot always passes. What this catches is the report
that *wasn't*: regenerated before the cap existed, produced with
``--figure-max-dpi 0``, or copied in from an older checkout. Those are
indistinguishable by eye and cost ~15 MB of permanent history each.

The check rests on one invariant from ``_render_figure_with_caption``: a figure
is placed at most ``usable_width`` wide, never wider, so on a Letter page with
15 mm margins no embedded raster can legitimately exceed

    (215.9 - 2*15) mm / 25.4 * 200 dpi = 1464 px

Figures constrained by page *height* are placed narrower still, so this is an
upper bound on every figure and cannot fire on a correctly generated report.

Run by pre-commit against staged ``reports/*.pdf``; also usable directly:

    python tools/check_report_figure_dpi.py reports/*.pdf
"""

import argparse
import sys

from pypdf import PdfReader

# asp_plot.report.ASPReportPDF: Letter portrait, set_margins(15, 15, 15).
PAGE_WIDTH_MM = 215.9
MARGIN_MM = 15.0
MM_PER_INCH = 25.4
FIGURE_MAX_DPI = 200

MAX_WIDTH_PX = round((PAGE_WIDTH_MM - 2 * MARGIN_MM) / MM_PER_INCH * FIGURE_MAX_DPI)
# A couple of pixels of slack for rounding in the resize and in fpdf2.
TOLERANCE_PX = 8


def oversized_images(path):
    """Yield (page_number, width, height) for each figure above the ceiling.

    Reads /Width and /Height straight off each image XObject rather than going
    through ``page.images``, which decodes the raster (and needs Pillow) to
    tell us something the dictionary already states.
    """
    reader = PdfReader(path)
    for page_no, page in enumerate(reader.pages, start=1):
        resources = page.get("/Resources")
        if resources is None:
            continue
        xobjects = resources.get_object().get("/XObject")
        if xobjects is None:
            continue
        for ref in xobjects.get_object().values():
            obj = ref.get_object()
            if obj.get("/Subtype") != "/Image":
                continue
            width = int(obj.get("/Width", 0))
            height = int(obj.get("/Height", 0))
            if width > MAX_WIDTH_PX + TOLERANCE_PX:
                yield page_no, width, height


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("paths", nargs="*", help="PDF files to check.")
    args = parser.parse_args(argv)

    failed = False
    for path in args.paths:
        offenders = list(oversized_images(path))
        if not offenders:
            continue
        failed = True
        print(f"\n{path}: {len(offenders)} figure(s) above {MAX_WIDTH_PX} px")
        for page_no, width, height in offenders[:5]:
            dpi = width / ((PAGE_WIDTH_MM - 2 * MARGIN_MM) / MM_PER_INCH)
            print(
                f"    page {page_no:>3}: {width}x{height} px (~{dpi:.0f} effective dpi)"
            )
        if len(offenders) > 5:
            print(f"    ... and {len(offenders) - 5} more")

    if failed:
        print(
            "\nThese reports were generated without the figure-resolution cap.\n"
            "Regenerate them with current asp_plot (see reports/regenerate_reports.sh);\n"
            "each uncapped report costs roughly 2x its size in permanent history.\n"
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
