# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Micromamba
      run: |
        curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
        ./bin/micromamba shell init -s bash -p ~/micromamba
        mkdir -p ~/micromamba/envs

    - name: Create and activate environment
      shell: bash -l {0}
      run: |
        export MAMBA_ROOT_PREFIX=~/micromamba
        export PATH=$PATH:~/micromamba/bin
        ./bin/micromamba create -n asp_plot -f environment.yml
        ./bin/micromamba activate asp_plot

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        export MAMBA_ROOT_PREFIX=~/micromamba
        export PATH=$PATH:~/micromamba/bin
        ./bin/micromamba activate asp_plot
        pip install .

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        export MAMBA_ROOT_PREFIX=~/micromamba
        export PATH=$PATH:~/micromamba/bin
        ./bin/micromamba activate asp_plot
        pytest
