# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Mamba
      run: |
        wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
        echo 'export PATH=$PATH:$HOME/bin' >> $GITHUB_ENV
        ./bin/micromamba shell init -s bash -p ~/micromamba
        source ~/.bashrc

    - name: Create conda environment
      run: |
        micromamba create -n asp_plot -f environment.yml
        micromamba activate asp_plot

    - name: Run tests
      run: |
        micromamba activate asp_plot
        pytest
