# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Micromamba
      run: |
        curl micro.mamba.pm/install.sh | bash
        echo 'export PATH=$HOME/.local/bin:$PATH' >> $GITHUB_ENV
    - name: Create and activate environment
      shell: bash -l {0}
      run: |
        micromamba create -n asp_plot -f environment.yml
        micromamba activate asp_plot
        echo "CONDA_PREFIX=$(micromamba info --base)" >> $GITHUB_ENV
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        micromamba activate asp_plot
        pip install .
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        micromamba activate asp_plot
        pytest
